Feature/vue/categories articles
WildCodeSchool/healthymood-back pull request #32
Opened 2020-06-16 21:41 UTC by abdel74100

2020-06-17 06:26 UTC, ComicScrip commented
merge please

2020-06-17 06:31 UTC, ComicScrip requested changes

2020-06-17 06:31 UTC, ComicScrip commented on src/components/EditorComponent.js
> +        apiKey='amntzl33pmjmf0hj96f03mr21hnr3lwuxt2dry7jsxi2wjdx'
A mettre dans une variable d'env

2020-06-17 06:31 UTC, ComicScrip commented on src/Styles/Form.css
> +		display: block;
indentation

2020-06-17 06:31 UTC, ComicScrip commented on src/dataService/data.service.js
> +fetch("https://world.openfoodfacts.org/api/v0/product/04963406")
code mort

2020-06-17 06:31 UTC, ComicScrip commented on src/dataService/data.service.js
> +function _getElements () {
L'idée de faire quelque chose de générique est bonne, mais il faudra revoir ça. On s'en parle en fin de semaine :)

2020-06-23 02:07 UTC, abdel74100 commented on src/components/EditorComponent.js
> +        apiKey='amntzl33pmjmf0hj96f03mr21hnr3lwuxt2dry7jsxi2wjdx'
created .env

2020-06-23 02:08 UTC, abdel74100 commented on src/dataService/data.service.js
> +fetch("https://world.openfoodfacts.org/api/v0/product/04963406")
deleted

2020-06-23 02:08 UTC, abdel74100 commented on src/dataService/data.service.js
> +function _getElements () {
deleted

2020-06-23 02:13 UTC, abdel74100 commented
done

2020-06-29 06:52 UTC, merged