Feature/crud/pages
WildCodeSchool/healthymood-back pull request #39
Opened 2020-07-02 12:48 UTC by Astarosa

@ComicScrip Fonctionne avec la branche dev de l'api

2020-07-02 14:44 UTC, ComicScrip commented
merge please

2020-07-02 14:53 UTC, Astarosa commented
@ComicScrip Merge done all good

2020-07-02 15:15 UTC, ComicScrip requested changes

2020-07-02 15:15 UTC, ComicScrip commented on .env
> +<<<<<<< HEAD
not good

2020-07-02 15:15 UTC, ComicScrip commented on src/components/FormArticleCategory.js
> +import React, { useState, useEffect } from 'react';
rien a faire dans cette PR

2020-07-02 15:15 UTC, ComicScrip commented on src/components/FormIngredient.js
> +import React, { useState, useEffect } from 'react';
Ca non plus...

2020-07-02 15:15 UTC, ComicScrip commented on src/components/FormRecipeCategory.js
> +import React, { useState } from 'react';
Ca non plus

2020-07-02 15:15 UTC, ComicScrip commented on src/dataService/data.service.js
> +let data = [];
a virer

2020-07-02 15:15 UTC, ComicScrip commented on src/pages/Pages.js
> +      user_id: userIdFromToken
a virer comme discuté hier...

2020-07-02 15:21 UTC, ComicScrip commented
Une fois que j'ai ajouté une page, je souhaite me retrouver la page de listing des pages.
Coup de peinture : faire en sorte que les éléments de formulaire prennent (presque) toute la largeur dispo pour plus de confort

2020-07-02 16:44 UTC, Astarosa commented on src/pages/Pages.js
> +      user_id: userIdFromToken
On a passé un ID en dur en attendant de le gérer dans l'api du coup ça te va ?

2020-07-02 16:46 UTC, Astarosa commented
@ComicScrip On a corrigé au mieux est-ce que ça te va ?

2020-07-03 08:17 UTC, Astarosa commented on src/components/FormArticleCategory.js
> +import React, { useState, useEffect } from 'react';
Réglé

2020-07-03 08:17 UTC, Astarosa commented on src/components/FormIngredient.js
> +import React, { useState, useEffect } from 'react';
Pareil

2020-07-03 08:17 UTC, Astarosa commented on src/components/FormRecipeCategory.js
> +import React, { useState } from 'react';
Retiré

2020-07-03 08:17 UTC, Astarosa commented on src/dataService/data.service.js
> +let data = [];
Retiré également

2020-07-03 08:18 UTC, Astarosa commented on .env
> +<<<<<<< HEAD
Résolu

2020-07-03 09:48 UTC, merged